name: Deploy Bicep files

trigger: 
# - main
- master

variables:
  resourceGroupName: 'rg-bicep-demo-0018'
  location: 'eastus'
  webAppName: 'bicep0018'
  templateFile: 'myfile.bicep'

pool:
  name: 'myPool'

steps:

- task: AzureCLI@2
  displayName: Create RG
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: 'powershell'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name $(resourceGroupName) --location $(location)
      az config set bicep.use_binary_from_path=false

# - task: AzureCLI@2
#   displayName: Preview Bicep Changes
#   inputs:
#     azureSubscription: 'azure-connection'
#     scriptType: 'powershell'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       az deployment group what-if --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters webAppName=$(webAppName)

# - task: AzureCLI@2
#   displayName: Preview Bicep Changes
#   inputs:
#     azureSubscription: 'azure-connection'
#     scriptType: 'powershell'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       az --version
#       az group create --name $(resourceGroupName) --location $(location)
#       az deployment group what-if --resource-group $(resourceGroupName) `
#             --template-file $(templateFile) `
#             --parameters webAppName=$(webAppName)

- task: AzureCLI@2
  displayName: Deploy Bicep To Azure
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: 'powershell'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters webAppName=$(webAppName)